kind: Namespace
apiVersion: v1
metadata:
  name: bing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: bing
spec:
  selector:
    matchLabels:
      app: registry
      version: "2.0"
  template:
    metadata:
      labels:
        app: registry
        version: "2.0"
    spec:
      containers:
      - name: registry
        image: registry:2.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: library
            mountPath: /var/lib/registry
      volumes:
        - name: library
          nfs:
            path: /data2/registry
            server: 192.168.0.248
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: bing
spec:
  selector:
    app: registry
    version: "2.0"
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
  type: NodePort
