apiVersion: v1
kind: Pod
metadata:
  name: demo-cpu-limit
spec:
  containers:
  - name: demo-cpu-limit
    image: registry.bing89.com/tools/demo:1.0
    ports:
    - containerPort: 8080
      name: http-port
    resources:
      limits:
        cpu: 100m
      requests:
        cpu: 50m
    restartPolicy: OnFailure